theme = "vonge"
title = "Charlie Hart"

# The URL the site will be built for
base_url = "https://chh92-eng.github.io/charliehart"



# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
ignore_theme_templates = true
author = "Charlie Hart"
bio = "Mechanical engineering student at Cornell interested in transportation, planning, and sustainability."
logo_image = "images/shell.svg"
author_image = '/images/charlie1.jpg'
social_media_share_image = "images/charlie1.jpg"
social_media_title = "Charlie Hart"
social_media_description = "Mechanical engineering student at Cornell University, passionate about transportation, design, and sustainability."


navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/projects", title = "Projects" },
    { url = "$BASE_URL/about", title = "About" },
    { url = "$BASE_URL/posts", title = "Blog" }
]


custom_css = ["css/custom.css"]

social_icons = [
    { url = "https://github.com/chh92-eng", icon = "GitHub" },
    { url = "https://www.linkedin.com/in/charlie-h-hart", icon = "Linkedin" },
    { url = "mailto:chh92@cornell.edu", icon = "/icons/mail.svg" }
]




# completely override the theme’s content blocks
# you can copy this whole section into your personal config.toml

# HERO
[[extra.content_blocks]]
block = "hero"
title = "Hi there, I’m Charlie Hart"
description_html = "<strong>Mechanical engineering student</strong> passionate about transportation, planning, and sustainability."
image = "/images/charlie1.jpg"
image_alt = "Charlie Hart headshot"
cta_button_link = "/projects"
cta_button = "See my work"
works_button_link = "/about"
works_button = "Learn more about me"

# PROJECTS
[[extra.content_blocks]]
block = "projects-section"
title = "Projects"
description_html = """
    <p>Some of my most recent work.</p>"""
link_url = "projects"
show_projects = true

# BLOG (optional)
[[extra.content_blocks]]
block = "blog-section"
title = "Posts"
description_html = """
    <p>Personal Updates</p>"""
link_url = "posts"
show_posts = true

# CONTACT (optional)
[[extra.content_blocks]]
block = "contact-form"
form_title = "Get in touch"
form_description = "Reach out — I’d love to hear from you."
form_success_page = ''
form_submission_email = "chh92@cornell.edu"
form_button_text = "Send"

